model_names:
  - deeplabv3plus

model:
  deeplabv3plus:
    backbone: resnet50
    in_channels: 4
    num_classes: 1
    batch_size: 4

data:
  num_workers:  4
  spark_catalog: land_topografisk-gdb_dev
  spark_schema: ai2025
  mode: "predict"
  predict:
    overview_table: nyendepunkt_status_overview
    id_field:       nodeid

logging:
  tracking_uri:    "databricks"