model_names:
  - unet

model:
  unet:
    backbone: resnet50
    in_channels: 3
    num_classes: 1
    batch_size: 8

data:
  num_workers:  0
  spark_catalog: land_auto-gen-kart_dev
  spark_schema: dl_bildesegmentering
  mode: "predict"
  predict:
    id_field: row_hash
    overview_table: hospitals_status_overview
    local_save_dir: predicted_helipads
    target: helipads

logging:
  tracking_uri: "databricks"