model_names:
  - deeplabv3plus

model:
  deeplabv3plus:
    backbone: resnet101
    in_channels: 4
    num_classes: 1
    lr: 0.0005

data:
  batch_size:   4
  num_workers:  4

  spark_catalog: land_topografisk-gdb_dev
  spark_schema: ai2025
  
  mode: "predict"
  predict:
    checkpoint_path: /Workspace/Users/fabian.heflo@kartverket.no/Snuplasser/src/model/modelsCheckpoints/deeplabv3plus_best.ckpt
    overview_table: endepunkt_status_overview
    id_field:       nodeid
    

# Valgfritt: om du fortsatt vil logge prediksjonene
logging:
  use_mlflow:     true
  experiment_name: /Users/fabian.heflo@kartverket.no/deeplabv3plus
  tracking_uri:    "databricks"
