model_names:
  - deeplabv3plus

model:
  deeplabv3plus:
    backbone: resnet101
    in_channels: 4
    num_classes: 1
    batch_size: 4
    lr: 0.0005

data:
  num_workers:  4
  spark_catalog: land_topografisk-gdb_dev
  spark_schema: ai2025
  mode: "predict"
  predict:
    overview_table: endepunkt_status_overview
    id_field:       nodeid

logging:
  tracking_uri:    "databricks"