model_names:
  - unet

model:
  unet:
    backbone: resnet50
    in_channels: 3
    num_classes: 1
    batch_size: 4

data:
  num_workers:  4
  spark_catalog: land_topografisk-gdb_dev
  spark_schema: ai2025
  mode: "predict"
  predict:
    id_field: row_hash
    overview_table: hospitals_status_overview
    local_save_dir: predicted_helipads
    target: helipads

logging:
  tracking_uri: "databricks"