model_names:
  - deeplabv3plus

model:
  deeplabv3plus:
    backbone: resnet101
    in_channels: 4
    num_classes: 1
    batch_size: 4
    lr: 0.0005

data:
  image_dir: /Volumes/land_topografisk-gdb_dev/external_dev/static_data/DL_SNUPLASSER/storreendepunkt_images/
  dom_dir:   /Volumes/land_topografisk-gdb_dev/external_dev/static_data/DL_SNUPLASSER/storreendepunkt_dom/
  batch_size:   4
  num_workers:  4

  spark_catalog: land_topografisk-gdb_dev
  spark_schema: ai2025
  
  mode: "predict"
  predict:
    overview_table: endepunkt_status_overview
    id_field:       nodeid
    

# Valgfritt: om du fortsatt vil logge prediksjonene
logging:
  use_mlflow:     true
  tracking_uri:    "databricks"
