model_names:
  - deeplabv3plus

model:
  deeplabv3plus:
    backbone: resnet101
    in_channels: 4
    num_classes: 1
    batch_size: 4
    lr: 0.0001

data:
  num_workers: 4              # DataLoader workers
  val_split: 0.2              # Valideringsandel
  holdout_size: 50
  seed: 42
  use_augmentation: false
  augmentation_ratio: 0.4
  flip_p: 0.3
  brightness_limit: 0.05
  contrast_limit: 0.05
  rotate_limit: 10
  scale_limit: 0.05
  gaussian_blur_p: 0.1
  elastic_transform_p: 0.1
  spark_catalog: land_topografisk-gdb_dev
  spark_schema: ai2025
  mode: "train"
  train:
    id_field: row_hash
    overview_table: train_silver # polygons_status_overview 

training:
  max_epochs: 100              # Antall epoker per kjøring
  precision: 16-mixed      # Mixed precision (16 eller 32)
  accelerator: gpu
  devices: 1                  # GPU-ressurser
  log_every_n_steps: 10
  early_stopping_patience: 15  # Stopper tidlig om validerings-loss ikke forbedres
  monitor: val_loss  # val_iou , Må logges av modellen og oppdateres i utils.callbacks
  monitor_mode: min  # max for IoU

log_predictions_callback:
  log_every_n_epochs: 2
  artifact_dir: "val_predictions"

logging:
  tracking_uri: "databricks" # Slik at eksperimenter og modeller kan lagres og sammenlignes sentralt

optuna:
  direction: maximize         # Hvilken vei metrikken skal optimaliseres
  metric_name: val_iou        # Navn på metrikken som returneres fra validate()
  n_trials: 50                # Antall eksperimenter
  n_jobs: 8                   # Skal matche antall workers på clusteret