model_names:
  - deeplabv3plus

model:
  deeplabv3plus:
    backbone: resnet101
    in_channels: 4
    num_classes: 1
    batch_size: 4
    lr: 0.0001

data:
  num_workers: 4 # Antall arbeidere på clusteret
  val_split: 0.2 # Valideringsandel
  holdout_size: 50
  seed: 42
  use_augmentation: false
  augmentation_ratio: 0.4
  flip_p: 0.3
  brightness_limit: 0.05
  contrast_limit: 0.05
  rotate_limit: 10
  scale_limit: 0.05
  gaussian_blur_p: 0.1
  elastic_transform_p: 0.1
  spark_catalog: land_topografisk-gdb_dev
  spark_schema: ai2025
  mode: "train"
  train:
    id_field: row_hash
    overview_table: train_silver # polygons_status_overview for å trene kun på snuplasser

training:
  max_epochs: 100 # Antall epoker per kjøring
  precision: 16-mixed # Mixed precision (16 eller 32)
  accelerator: gpu # cpu hvis det kjøres lokalt
  devices: 1 # GPU-ressurser
  log_every_n_steps: 10
  early_stopping_patience: 15  # Stopper tidlig om valideringstap ikke forbedres
  monitor: val_loss  # Kan bruke val_iou, må logges av modellen og oppdateres i utils.callbacks
  monitor_mode: min  # max ved IoU

log_predictions_callback:
  log_every_n_epochs: 2 # Logger prediksjonene etter annenhver epoch
  artifact_dir: "val_predictions"

logging:
  tracking_uri: "databricks" # Slik at eksperimenter og modeller kan lagres og sammenlignes sentralt

optuna:
  direction: maximize # Hvilken vei metrikken skal optimaliseres
  metric_name: val_iou # Navn på metrikken som returneres fra validate()
  n_trials: 50 # Antall eksperimenter
  n_jobs: 8 # Skal matche antall workers på clusteret